//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerNetwork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BrokerNetworkConnection : DbContext
    {
        public BrokerNetworkConnection()
            : base("name=BrokerNetworkConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyBroker> CompanyBrokers { get; set; }
        public virtual DbSet<CompanyType> CompanyTypes { get; set; }
        public virtual DbSet<CompanyVerificationType> CompanyVerificationTypes { get; set; }
        public virtual DbSet<CusomerPreview> CusomerPreviews { get; set; }
        public virtual DbSet<Customer_CustomerStatus> Customer_CustomerStatus { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerStatu> CustomerStatus { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FilesLine> FilesLines { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<OwnerShipType> OwnerShipTypes { get; set; }
        public virtual DbSet<Permission_PermissionGroup> Permission_PermissionGroup { get; set; }
        public virtual DbSet<PermissionGroup> PermissionGroups { get; set; }
        public virtual DbSet<PreviewStatu> PreviewStatus { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectStatu> ProjectStatus { get; set; }
        public virtual DbSet<ProjectType> ProjectTypes { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<PropertyFloorType> PropertyFloorTypes { get; set; }
        public virtual DbSet<PropertyPicture> PropertyPictures { get; set; }
        public virtual DbSet<PropertyPurpose> PropertyPurposes { get; set; }
        public virtual DbSet<PropertyRequest> PropertyRequests { get; set; }
        public virtual DbSet<PropertyRequests_FollowUp> PropertyRequests_FollowUp { get; set; }
        public virtual DbSet<PropertyType> PropertyTypes { get; set; }
        public virtual DbSet<RequestStatu> RequestStatus { get; set; }
        public virtual DbSet<Shared> Shareds { get; set; }
        public virtual DbSet<SpecialOffer> SpecialOffers { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<User_UserPermission> User_UserPermission { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<UserPermission> UserPermissions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VerficationRequest> VerficationRequests { get; set; }
        public virtual DbSet<VerficationStatu> VerficationStatus { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
    }
}
