//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long CommentID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> PostID { get; set; }
        public Nullable<int> PostType { get; set; }
        public string CommentMsg { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
