//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.CompanyBrokers = new HashSet<CompanyBroker>();
            this.Projects = new HashSet<Project>();
            this.Users = new HashSet<User>();
            this.VerficationRequests = new HashSet<VerficationRequest>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyDesc { get; set; }
        public int CompanyVerificationTypeID { get; set; }
        public string Address { get; set; }
        public int CompanyTypeID { get; set; }
        public string Email { get; set; }
        public string Contacts { get; set; }
        public string ImgPath { get; set; }
        public long ByUserID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string ContactsForBrokers { get; set; }
    
        public virtual CompanyType CompanyType { get; set; }
        public virtual CompanyVerificationType CompanyVerificationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyBroker> CompanyBrokers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VerficationRequest> VerficationRequests { get; set; }
    }
}
