//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyBroker
    {
        public long CompanyBrokerID { get; set; }
        public int CompanyID { get; set; }
        public long UserID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
