//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CusomerPreview
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CusomerPreview()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public long CustomerPreviewID { get; set; }
        public long PropertyID { get; set; }
        public long CustomerID { get; set; }
        public System.DateTime PreviewDate { get; set; }
        public Nullable<System.TimeSpan> PreviewTime { get; set; }
        public int PreviewStatusID { get; set; }
        public int NoOfProperties { get; set; }
        public string ShawAlertBeforeMinutes { get; set; }
        public string Comments { get; set; }
        public long ByUserID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PreviewStatu PreviewStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
