//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CusomerPreviews = new HashSet<CusomerPreview>();
            this.Customer_CustomerStatus = new HashSet<Customer_CustomerStatus>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public long CustomerID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public int CustomerStatusID { get; set; }
        public string CustomerName { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ByUserID { get; set; }
        public string Comments { get; set; }
        public System.DateTime EntryDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CusomerPreview> CusomerPreviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_CustomerStatus> Customer_CustomerStatus { get; set; }
        public virtual CustomerStatu CustomerStatu { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
