//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilesLine
    {
        public long FilesLineID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string ParentTypeID { get; set; }
        public string Path { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
