//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission_PermissionGroup
    {
        public int ID { get; set; }
        public int PermissionGroupID { get; set; }
        public int UserPermissionID { get; set; }
        public long ByUserID { get; set; }
    
        public virtual PermissionGroup PermissionGroup { get; set; }
        public virtual UserPermission UserPermission { get; set; }
    }
}
