//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.PropertyPictures = new HashSet<PropertyPicture>();
        }
    
        public long PropertyID { get; set; }
        public string Title { get; set; }
        public int CustomerID { get; set; }
        public long ByUserID { get; set; }
        public int LocationID { get; set; }
        public string AddressDetails { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public bool IsUnit { get; set; }
        public decimal Price { get; set; }
        public bool CanInstallment { get; set; }
        public Nullable<int> NoOfYears { get; set; }
        public Nullable<decimal> DownPayment { get; set; }
        public int FloorNum { get; set; }
        public int PropertyFloorTypeID { get; set; }
        public int NoOfProperties { get; set; }
        public int Area { get; set; }
        public int OwnerShipTypeID { get; set; }
        public int PropertyTypeID { get; set; }
        public int PropertyPurposeID { get; set; }
        public bool HasElevator { get; set; }
        public bool HasGarage { get; set; }
        public bool AllowVisitors { get; set; }
        public Nullable<double> Commission { get; set; }
        public int NumberOfRooms { get; set; }
        public int NumberOfBathrooms { get; set; }
        public System.DateTime ReadyDate { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string SharedID { get; set; }
        public string Comments { get; set; }
        public System.DateTime EntryDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CommissionType { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual OwnerShipType OwnerShipType { get; set; }
        public virtual Project Project { get; set; }
        public virtual PropertyFloorType PropertyFloorType { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual PropertyPurpose PropertyPurpose { get; set; }
        public virtual Shared Shared { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyPicture> PropertyPictures { get; set; }
    }
}
