//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyRequest()
        {
            this.PropertyRequests_FollowUp = new HashSet<PropertyRequests_FollowUp>();
        }
    
        public long RequestID { get; set; }
        public string Title { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> LocationIDs { get; set; }
        public string AddressDetails { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public bool CanInstallment { get; set; }
        public Nullable<int> NoOfYears { get; set; }
        public Nullable<int> PropertyFloorTypeID { get; set; }
        public Nullable<int> MinArea { get; set; }
        public Nullable<int> MaxArea { get; set; }
        public Nullable<int> OwnerShipTypeID { get; set; }
        public Nullable<int> PropertyTypeID { get; set; }
        public Nullable<int> PropertyPurposeID { get; set; }
        public string Comments { get; set; }
        public long ByUserID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> GovID { get; set; }
        public Nullable<int> CityID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual OwnerShipType OwnerShipType { get; set; }
        public virtual PropertyFloorType PropertyFloorType { get; set; }
        public virtual PropertyPurpose PropertyPurpose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyRequests_FollowUp> PropertyRequests_FollowUp { get; set; }
        public virtual PropertyType PropertyType { get; set; }
    }
}
