//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyRequests_FollowUp
    {
        public long FollowUpID { get; set; }
        public long RequestID { get; set; }
        public int RequestStatusID { get; set; }
        public string Comments { get; set; }
        public long ByUserID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual PropertyRequest PropertyRequest { get; set; }
        public virtual RequestStatu RequestStatu { get; set; }
    }
}
