//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long PreviewID { get; set; }
        public long TransactionID { get; set; }
        public long PropertyID { get; set; }
        public long CustomerID { get; set; }
        public System.DateTime PreviewDate { get; set; }
        public Nullable<System.TimeSpan> PreviewTime { get; set; }
        public string Reason { get; set; }
        public int PreviewStatusID { get; set; }
        public long ByUserID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual CusomerPreview CusomerPreview { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
