//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_UserPermission
    {
        public int ID { get; set; }
        public long UserID { get; set; }
        public int UserPermissionID { get; set; }
        public long ByUserID { get; set; }
    
        public virtual UserPermission UserPermission { get; set; }
        public virtual User User { get; set; }
    }
}
