//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerficationRequest
    {
        public long VerficationID { get; set; }
        public long UserID { get; set; }
        public int CompanyID { get; set; }
        public string RequestContent { get; set; }
        public Nullable<int> VerfiedStatusID { get; set; }
        public string AdminMessage { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
        public virtual VerficationStatu VerficationStatu { get; set; }
    }
}
